In [1]:
#pip install pandas

In [2]:
#pip install matplotlib

In [3]:
#pip install scipy

In [4]:
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import json
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns', None)
#BASE URL
BaseURL = 'https://api-web.nhle.com'

In [5]:
# STARTINGCSV2023=pd.read_csv('LastYear2023Stats.csv')  
# STARTINGCSV2024=pd.read_csv('ThisYear2024Stats.csv')  
#STARTINGCSV2025=pd.read_csv('NHL2526seasonplayerstats.csv')  
STARTINGCSV2025=pd.read_csv('NewPlayerStats2526.csv')  

STARTINGCSV=STARTINGCSV2025#pd.concat([STARTINGCSV2023, STARTINGCSV2024])

STARTINGCSV.sort_values(by=['gameId'])
STARTINGCSV[STARTINGCSV['homeRoadFlag']==1]

,playerId,sweaterNumber,name,position,goals,assists,points,plusMinus,pim,hits,powerPlayGoals,sog,faceoffWinningPctg,toi,blockedShots,shifts,giveaways,takeaways,firstName,lastName,Team,gameId,homeRoadFlag
12,8477935,9,{'default': 'S. Bennett'},C,0,0,0,-1,0,1,0,4,0.555556,19:15,0,26,0,1,Sam,Bennett,FLA,2025020001,1
13,8478421,10,{'default': 'A. Greer'},L,1,0,1,1,5,5,0,1,0.000000,07:19,1,13,0,0,A.J.,Greer,FLA,2025020001,1
14,8482713,11,{'default': 'M. Samoskevich'},R,0,2,2,1,0,3,0,0,0.000000,11:18,0,21,0,0,Mackie,Samoskevich,FLA,2025020001,1
15,8479981,12,{'default': 'J. Gadjovich'},L,0,1,1,1,0,4,0,1,0.000000,07:18,1,12,0,1,Jonah,Gadjovich,FLA,2025020001,1
16,8477933,13,{'default': 'S. Reinhart'},C,0,0,0,-1,0,1,0,3,0.333333,18:14,2,23,2,0,Sam,Reinhart,FLA,2025020001,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19647,8475200,9,{'default': 'D. Orlov'},D,0,0,0,1,0,3,0,1,0.000000,23:40,2,23,1,1,Dmitry,Orlov,SJS,2025020543,1
19648,8482861,22,{'default': 'V. Iorio'},D,0,0,0,0,0,1,0,0,0.000000,14:02,0,21,0,0,Vincent,Iorio,SJS,2025020543,1
19649,8480043,37,{'default': 'T. Liljegren'},D,0,0,0,1,0,2,0,1,0.000000,20:46,1,23,1,0,Timothy,Liljegren,SJS,2025020543,1
19650,8479983,38,{'default': 'M. Ferraro'},D,0,0,0,-1,0,3,0,2,0.000000,17:31,1,21,2,0,Mario,Ferraro,SJS,2025020543,1
19651,8482166,85,{'default': 'S. Mukhamadullin'},D,1,0,1,0,2,1,0,1,0.000000,11:53,2,18,2,0,Shakir,Mukhamadullin,SJS,2025020543,1

In [6]:
# #https://medium.com/@alexandre.tkint/send-pandas-data-frame-via-email-in-python-c346314321fa


# from email.mime.application import MIMEApplication
# from email.mime.multipart import MIMEMultipart
# from email.mime.text import MIMEText
# import smtplib
# def send_email(send_to, subject, df):
#     send_from = "dummy@gmail.com"
#     password = "your_password"
#     message = """\
#     <p><strong>This is a test email&nbsp;</strong></p>
#     <p><br></p>
#     <p><strong>Greetings&nbsp;</strong><br><strong>Alexandre&nbsp;    </strong></p>
#     """
# for receiver in send_to:
#         multipart = MIMEMultipart()
#         multipart["From"] = send_from
#         multipart["To"] = receiver
#         multipart["Subject"] = subject  
#         attachment = MIMEApplication(df.to_csv())
#         attachment["Content-Disposition"] = 'attachment; filename=" {}"'.format(f"{subject}.csv")
#         multipart.attach(attachment)
#         multipart.attach(MIMEText(message, "html"))
#         server = smtplib.SMTP("smtp.gmail.com", 587)
#         server.starttls()
#         server.login(multipart["From"], password)
#         server.sendmail(multipart["From"], multipart["To"], multipart.as_string())
#         server.quit()

In [7]:
#TEAMS
import requests

link = BaseURL+'/v1/standings/now'
f = requests.get(link)

i=0
teamlist=[]
abbrevlist=[]
citylist=[]

while ((len(teamlist)<32)|(len(teamlist)<32)):
    try:
        citylist.append(f.json()['standings'][i]['placeName']['default'])
        teamlist.append(f.json()['standings'][i]['teamCommonName']['default'])
        abbrevlist.append(f.json()['standings'][i]['teamAbbrev']['default'])
        #teamlist=list(set(teamlist))
        i=i+1
    except:
        break
len(teamlist)

Teams=pd.DataFrame()
Teams['City']=citylist
Teams['TeamName']=teamlist
Teams['TeamID']=abbrevlist
Teams

            City        TeamName TeamID
0       Colorado       Avalanche    COL
1         Dallas           Stars    DAL
2      Minnesota            Wild    MIN
3       Carolina      Hurricanes    CAR
4          Vegas  Golden Knights    VGK
5     Washington        Capitals    WSH
6        Anaheim           Ducks    ANA
7   NY Islanders       Islanders    NYI
8        Detroit       Red Wings    DET
9   Philadelphia          Flyers    PHI
10      Montréal       Canadiens    MTL
11        Boston          Bruins    BOS
12      Edmonton          Oilers    EDM
13     Tampa Bay       Lightning    TBL
14    New Jersey          Devils    NJD
15   Los Angeles           Kings    LAK
16       Florida        Panthers    FLA
17    NY Rangers         Rangers    NYR
18    Pittsburgh        Penguins    PIT
19      San Jose          Sharks    SJS
20          Utah         Mammoth    UTA
21        Ottawa        Senators    OTT
22       Toronto     Maple Leafs    TOR
23       Buffalo          Sabres    BUF
24      Columbus    Blue Jackets    CBJ
25     St. Louis           Blues    STL
26      Winnipeg            Jets    WPG
27       Chicago      Blackhawks    CHI
28       Calgary          Flames    CGY
29       Seattle          Kraken    SEA
30     Nashville       Predators    NSH
31     Vancouver         Canucks    VAN

In [8]:
STARTINGCSV.head()

,playerId,sweaterNumber,name,position,goals,assists,points,plusMinus,pim,hits,powerPlayGoals,sog,faceoffWinningPctg,toi,blockedShots,shifts,giveaways,takeaways,firstName,lastName,Team,gameId,homeRoadFlag
0,8477987,8,{'default': 'R. Donato'},C,0,0,0,0,0,3,0,1,0.000000,16:00,0,23,0,0,Ryan,Donato,CHI,2025020001,0
1,8477450,16,{'default': 'J. Dickinson'},C,0,0,0,0,0,0,0,1,0.578947,14:14,0,25,0,0,Jason,Dickinson,CHI,2025020001,0
2,8473422,17,{'default': 'N. Foligno'},L,0,0,0,-1,5,2,0,0,0.625000,11:48,0,21,2,0,Nick,Foligno,CHI,2025020001,0
3,8483450,20,{'default': 'R. Greene'},C,0,0,0,-1,0,0,0,0,0.250000,08:17,0,15,0,0,Ryan,Greene,CHI,2025020001,0
4,8478043,24,{'default': 'S. Lafferty'},C,0,0,0,-1,0,1,0,0,0.000000,08:07,0,13,0,0,Sam,Lafferty,CHI,2025020001,0

In [9]:
playerStats=STARTINGCSV[['Team','playerId','firstName','lastName','gameId','homeRoadFlag','sog','toi','position']]
playerStats['toi']=round(pd.to_numeric(playerStats['toi'].str.slice(0,2).str.replace(':', '', regex=False)
                                 )+(pd.to_numeric(playerStats['toi'].str.slice(3, 5))/60),2) #min+sec in decimal base not base60
playerStats['GameNumber'] = playerStats.groupby(['playerId'])['gameId'].cumcount(ascending=False)+1
playerStats['GP']=playerStats.groupby('Team').GameNumber.transform(np.max)
playerStats['HomeGames'] = playerStats.groupby(['playerId']).homeRoadFlag.transform(np.sum)
playerStats['AwayGames']=playerStats['GP']-playerStats['HomeGames']
playerStats['TotalShotsSzn']=playerStats.groupby(['playerId']).sog.transform(np.sum)
playerStats['SeasonAvgSOG']= round(playerStats['TotalShotsSzn']/playerStats['GP'],2)
playerStats['AvgShotsSznByLoc']=playerStats.groupby(['playerId','homeRoadFlag']).sog.transform(np.mean)

playerStats['LastFiveFlag'] = np.where(playerStats['GameNumber'] >= playerStats['GP']-5, 1, 0)
playerStats['LastFiveAvgShots']=playerStats.groupby(['playerId','LastFiveFlag']).sog.transform(np.sum)/5
playerStats['LastFiveAvgShots']=np.where(playerStats['LastFiveFlag'] == 1, playerStats['LastFiveAvgShots'], 0)
playerStats['LastFiveAvgShots']=playerStats.groupby('playerId').LastFiveAvgShots.transform(np.max)

playerStats['LastTenFlag'] = np.where(playerStats['GameNumber'] >= playerStats['GP']-10, 1, 0)
playerStats['LastTenAvgShots']=playerStats.groupby(['playerId','LastTenFlag']).sog.transform(np.sum)/10
playerStats['LastTenAvgShots']=np.where(playerStats['LastTenFlag'] == 1, playerStats['LastTenAvgShots'], 0)
playerStats['LastTenAvgShots']=playerStats.groupby('playerId').LastTenAvgShots.transform(np.max)

playerStats['avgshotshomevaway']=round(playerStats.groupby(['playerId','homeRoadFlag']).sog.transform(np.mean),2)


playerStats[playerStats['homeRoadFlag']==1]

,Team,playerId,firstName,lastName,gameId,homeRoadFlag,sog,toi,position,GameNumber,GP,HomeGames,AwayGames,TotalShotsSzn,SeasonAvgSOG,AvgShotsSznByLoc,LastFiveFlag,LastFiveAvgShots,LastTenFlag,LastTenAvgShots,avgshotshomevaway
12,FLA,8477935,Sam,Bennett,2025020001,1,4,19.25,C,33,33,19,14,76,2.30,2.631579,1,3.0,1,2.2,2.63
13,FLA,8478421,A.J.,Greer,2025020001,1,1,7.32,L,33,33,19,14,38,1.15,1.473684,1,0.4,1,0.6,1.47
14,FLA,8482713,Mackie,Samoskevich,2025020001,1,0,11.30,R,33,33,19,14,73,2.21,2.000000,1,2.4,1,2.7,2.00
15,FLA,8479981,Jonah,Gadjovich,2025020001,1,1,7.30,L,10,33,5,28,8,0.24,1.200000,0,0.0,0,0.0,1.20
16,FLA,8477933,Sam,Reinhart,2025020001,1,3,18.23,C,33,33,19,14,85,2.58,2.578947,1,3.0,1,3.5,2.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19647,SJS,8475200,Dmitry,Orlov,2025020543,1,1,23.67,D,1,35,19,16,40,1.14,1.263158,0,2.0,0,1.5,1.26
19648,SJS,8482861,Vincent,Iorio,2025020543,1,0,14.03,D,1,35,5,30,4,0.11,0.600000,0,0.0,0,0.0,0.60
19649,SJS,8480043,Timothy,Liljegren,2025020543,1,1,20.77,D,1,35,17,18,18,0.51,0.705882,0,0.0,0,0.4,0.71
19650,SJS,8479983,Mario,Ferraro,2025020543,1,2,17.52,D,1,35,19,16,35,1.00,1.157895,0,1.8,0,1.3,1.16
19651,SJS,8482166,Shakir,Mukhamadullin,2025020543,1,1,11.88,D,1,35,11,24,13,0.37,0.909091,0,0.0,0,0.0,0.91

In [10]:
res = playerStats.groupby(['playerId'])["sog"].quantile([0.05, 0.95]).unstack(level=1)
res.reset_index(inplace=True)
res=res.set_axis(['playerId','Low','High'], axis=1)
res=playerStats.merge(res,on=['playerId'],how='left')
ShotsNoOutliers=res[(res['Low']<res['sog'])&(res['sog']<res['High'])].drop(columns=['Low', 'High'])

#toi
res = playerStats.groupby(['playerId'])["toi"].quantile([0.05, 0.95]).unstack(level=1)
res.reset_index(inplace=True)
res=res.set_axis(['playerId','Low','High'], axis=1)
res=ShotsNoOutliers.merge(res,on=['playerId'],how='left')
ShotsNoOutliers=res[(res['Low']<res['toi'])&(res['toi']<res['High'])].drop(columns=['Low', 'High'])

ShotsNoOutliers['Avgtoi']=ShotsNoOutliers.groupby(['playerId']).toi.transform(np.mean)

ShotsNoOutliers['GameNumberShotsNoOut'] = ShotsNoOutliers.groupby(['playerId'])['sog'].cumcount(ascending=False)+1
ShotsNoOutliers['GPShotsNoOut']=ShotsNoOutliers.groupby(['playerId']).GameNumberShotsNoOut.transform(np.max)
ShotsNoOutliers['NoOutliersAvgSOG']= ShotsNoOutliers.groupby(['playerId']).sog.transform(np.sum)/ShotsNoOutliers['GPShotsNoOut']
ShotsNoOutliers=ShotsNoOutliers[ShotsNoOutliers['NoOutliersAvgSOG']>1.3]
ShotsNoOutliers

,Team,playerId,firstName,lastName,gameId,homeRoadFlag,sog,toi,position,GameNumber,GP,HomeGames,AwayGames,TotalShotsSzn,SeasonAvgSOG,AvgShotsSznByLoc,LastFiveFlag,LastFiveAvgShots,LastTenFlag,LastTenAvgShots,avgshotshomevaway,Avgtoi,GameNumberShotsNoOut,GPShotsNoOut,NoOutliersAvgSOG
0,CHI,8477987,Ryan,Donato,2025020001,0,1,16.00,C,34,34,16,18,57,1.68,1.388889,1,3.0,1,2.5,1.39,15.122381,21,21,1.904762
1,CHI,8477450,Jason,Dickinson,2025020001,0,1,14.23,C,21,34,10,24,28,0.82,1.363636,0,0.0,0,0.0,1.36,16.012500,12,12,1.333333
2,CHI,8482703,Colton,Dach,2025020001,0,1,13.48,C,34,34,16,18,42,1.24,1.277778,1,1.6,1,1.4,1.28,12.467222,18,18,1.333333
3,CHI,8477479,Tyler,Bertuzzi,2025020001,0,1,19.17,L,31,34,13,21,66,1.94,2.277778,1,1.0,1,1.7,2.28,18.155714,21,21,2.190476
4,CHI,8476882,Teuvo,Teravainen,2025020001,0,1,18.08,C,33,34,16,18,37,1.09,0.882353,1,0.6,1,1.1,0.88,19.022941,17,17,1.352941
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11709,SJS,8477505,Alexander,Wennberg,2025020543,1,2,20.98,C,1,35,19,16,44,1.26,1.263158,0,1.4,0,1.2,1.26,20.499048,1,21,1.428571
11710,SJS,8475726,Tyler,Toffoli,2025020543,1,2,18.82,C,1,35,19,16,77,2.20,2.315789,0,2.6,0,2.6,2.32,15.797692,1,26,1.961538
11712,SJS,8478874,Adam,Gaudette,2025020543,1,1,12.77,R,1,35,14,21,42,1.20,1.571429,0,0.0,0,0.8,1.57,12.023529,1,17,1.588235
11713,DAL,8480036,Miro,Heiskanen,2025020543,0,1,23.80,D,1,35,17,18,76,2.17,1.722222,0,3.0,0,2.8,1.72,25.725909,1,22,2.045455
11715,DAL,8481581,Thomas,Harley,2025020543,0,1,22.00,D,1,35,11,24,26,0.74,1.083333,0,0.0,0,0.0,1.08,22.332000,1,10,1.500000

In [11]:
import datetime
# todaysindex=datetime.datetime.today().weekday()+2
# if  todaysindex>6:
#     todaysindex-=7
#I think todaysindex is always 3
todaysindex=3

TodaysGames=pd.DataFrame()
link = BaseURL + '/v1/scoreboard/now' 
f = requests.get(link)
df=pd.DataFrame(f.json()['gamesByDate'][todaysindex]['games'])

for i in range(0,len(df)):
    link = BaseURL + '/v1/scoreboard/now' 
    f = requests.get(link)
    AwayTeam=f.json()['gamesByDate'][todaysindex]['games'][i]['awayTeam']['abbrev']
    HomeTeam=f.json()['gamesByDate'][todaysindex]['games'][i]['homeTeam']['abbrev']

    dict = {'AwayTeam':[AwayTeam], 
        'HomeTeam':[HomeTeam]} 

    ThisGame=pd.DataFrame(dict)
    TodaysGames=pd.concat([TodaysGames,ThisGame], ignore_index = True)

TodaysGames

  AwayTeam HomeTeam
0      CAR      FLA
1      VAN      NYI
2      WPG      COL
3      NJD      UTA
4      DAL      ANA

In [12]:
shotSummary=ShotsNoOutliers[['Team', 'playerId','firstName', 'lastName', 'Avgtoi','position','SeasonAvgSOG', 'LastFiveAvgShots',
'LastTenAvgShots', 'NoOutliersAvgSOG','avgshotshomevaway']].drop_duplicates()

teamsPlayingToday=TodaysGames['AwayTeam'].tolist()+TodaysGames['HomeTeam'].tolist()
allgames=pd.concat([TodaysGames,TodaysGames[['HomeTeam','AwayTeam']].rename(
    columns={"AwayTeam": "HomeTeam","HomeTeam": "AwayTeam"})], ignore_index = True)

todaysSkaters=shotSummary[shotSummary['Team'].isin(teamsPlayingToday)]

todaysSkaters=todaysSkaters.merge(allgames.rename(columns={"AwayTeam": "Opponent"})
                                  , left_on='Team', right_on='HomeTeam', how='left').drop(columns=['HomeTeam'])
todaysSkaters['HomeFlag'] = np.where(todaysSkaters['Team'].isin(TodaysGames['HomeTeam'].tolist()), 1, 0)

todaysSkaters.sort_values(by=['NoOutliersAvgSOG']
                        , ascending=False #or True for players trending down
                       ).reset_index(drop=True).head(20)

,Team,playerId,firstName,lastName,Avgtoi,position,SeasonAvgSOG,LastFiveAvgShots,LastTenAvgShots,NoOutliersAvgSOG,avgshotshomevaway,Opponent,HomeFlag
0,COL,8477492,Nathan,MacKinnon,22.275455,C,4.73,5.0,4.9,4.727273,5.00,WPG,1
1,COL,8477492,Nathan,MacKinnon,22.275455,C,4.73,5.0,4.9,4.727273,4.50,WPG,1
2,NJD,8481559,Jack,Hughes,21.368333,C,2.03,0.0,0.0,4.166667,2.78,UTA,0
3,NJD,8481559,Jack,Hughes,21.368333,C,2.03,0.0,0.0,4.166667,5.50,UTA,0
4,ANA,8483445,Cutter,Gauthier,18.040417,L,3.74,5.6,5.2,3.958333,3.40,DAL,1
5,ANA,8483445,Cutter,Gauthier,18.040417,L,3.74,5.6,5.2,3.958333,4.00,DAL,1
6,DAL,8480027,Jason,Robertson,19.766538,L,3.86,5.2,4.7,3.884615,4.33,ANA,0
7,DAL,8480027,Jason,Robertson,19.766538,L,3.86,5.2,4.7,3.884615,3.35,ANA,0
8,NYI,8477500,Bo,Horvat,20.987619,C,3.26,4.6,3.4,3.714286,3.07,VAN,1
9,NYI,8477500,Bo,Horvat,20.987619,C,3.26,4.6,3.4,3.714286,3.82,VAN,1
10,WPG,8478398,Kyle,Connor,20.737826,L,3.33,3.6,3.9,3.608696,2.82,COL,0
11,WPG,8478398,Kyle,Connor,20.737826,L,3.33,3.6,3.9,3.608696,3.88,COL,0
12,CAR,8482093,Seth,Jarvis,19.715455,C,3.21,4.8,4.0,3.318182,3.69,FLA,0
13,CAR,8482093,Seth,Jarvis,19.715455,C,3.21,4.8,4.0,3.318182,2.76,FLA,0
14,UTA,8479343,Clayton,Keller,19.166538,R,2.86,3.0,2.9,3.153846,2.73,NJD,1
15,UTA,8479343,Clayton,Keller,19.166538,R,2.86,3.0,2.9,3.153846,3.07,NJD,1
16,NYI,8485366,Matthew,Schaefer,23.862000,D,2.74,3.8,3.3,3.100000,2.50,VAN,1
17,NYI,8485366,Matthew,Schaefer,23.862000,D,2.74,3.8,3.3,3.100000,2.94,VAN,1
18,FLA,8477409,Carter,Verhaeghe,17.753889,C,2.48,2.6,2.8,2.944444,2.29,CAR,1
19,FLA,8477409,Carter,Verhaeghe,17.753889,C,2.48,2.6,2.8,2.944444,2.78,CAR,1

In [13]:

goalieSTARTINGCSV2025=pd.read_csv('NewGoalieStats2526.csv')  
goalieSTARTINGCSV=goalieSTARTINGCSV2025
goalieSTARTINGCSV.sort_values(by=['gameId'])

,playerId,sweaterNumber,name,position,evenStrengthShotsAgainst,powerPlayShotsAgainst,shorthandedShotsAgainst,saveShotsAgainst,savePctg,evenStrengthGoalsAgainst,powerPlayGoalsAgainst,shorthandedGoalsAgainst,pim,goalsAgainst,toi,starter,decision,shotsAgainst,saves,firstName,lastName,Team,gameId,homeRoadFlag
0,8481519,30,{'default': 'S. Knight'},G,29/31,4/5,1/1,34/37,0.918919,2,1,0,0,3,59:04,True,L,37,34,Spencer,Knight,CHI,2025020001,0
1,8475683,72,"{'default': 'S. Bobrovsky', 'cs': 'S. Bobrovsk...",G,15/17,2/2,0/0,17/19,0.894737,2,0,0,0,2,60:00,True,W,19,17,Sergei,Bobrovsky,FLA,2025020001,1
2,8481668,37,"{'default': 'A. Silovs', 'cs': 'A. Šilovs', 's...",G,22/22,3/3,0/0,25/25,1.000000,0,0,0,0,0,60:00,True,W,25,25,Arturs,Silovs,PIT,2025020002,0
3,8478048,31,"{'default': 'I. Shesterkin', 'cs': 'I. Šesťork...",G,28/29,0/0,0/0,28/29,0.965517,1,0,0,0,1,59:37,True,L,29,28,Igor,Shesterkin,NYR,2025020002,1
4,8475809,41,{'default': 'S. Wedgewood'},G,17/17,7/8,0/0,24/25,0.960000,0,1,0,0,1,59:53,True,W,25,24,Scott,Wedgewood,COL,2025020003,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1091,8476412,50,{'default': 'J. Binnington'},G,22/23,6/7,1/1,29/31,0.935484,1,1,0,0,2,62:21,True,O,31,29,Jordan,Binnington,STL,2025020541,1
1092,8478916,35,{'default': 'J. Daccord'},G,31/33,10/11,1/1,42/45,0.933333,2,1,0,0,3,57:47,True,L,45,42,Joey,Daccord,SEA,2025020542,0
1093,8481692,32,{'default': 'D. Wolf'},G,21/22,0/1,0/0,21/23,0.913043,1,1,0,0,2,59:54,True,W,23,21,Dustin,Wolf,CGY,2025020542,1
1094,8479979,29,{'default': 'J. Oettinger'},G,27/30,7/7,0/0,34/37,0.918919,3,0,0,0,3,60:00,True,W,37,34,Jake,Oettinger,DAL,2025020543,0
1095,8477968,33,{'default': 'A. Nedeljkovic'},G,24/27,0/1,1/1,25/29,0.862069,3,1,0,0,4,58:04,True,L,29,25,Alex,Nedeljkovic,SJS,2025020543,1

In [14]:
goalieStats=goalieSTARTINGCSV[['Team','playerId','firstName','lastName','gameId','starter','shotsAgainst','goalsAgainst','savePctg']]

goalieStats['PlayerGameNumber'] = goalieStats.groupby(['playerId'])['gameId'].cumcount(ascending=False)+1
goalieStats['TeamGameNumber'] = goalieStats.groupby(['Team'])['gameId'].cumcount(ascending=False)+1
goalieStats['PlayerGP']=goalieStats.groupby(['playerId']).starter.transform(np.sum)
goalieStats['TeamGP']=goalieStats.groupby(['Team']).starter.transform(np.sum)

goalieStats['AvgShotsAgainst']=goalieStats.groupby(['Team']).shotsAgainst.transform(np.sum)/goalieStats['TeamGP']
goalieStats['RankAvgShotsAgainst']=round(goalieStats['AvgShotsAgainst'].rank(pct=True)*100,2)

goalieStats['AvgGoalsAgainst']=goalieStats.groupby(['playerId']).goalsAgainst.transform(np.sum)/goalieStats['PlayerGP']
goalieStats['RankAvgGoalsAgainst']=round(goalieStats['AvgGoalsAgainst'].rank(pct=True)*100,2)

goalieStats['AvgSavePctg']=goalieStats.groupby(['playerId']).savePctg.transform(np.sum)/goalieStats['PlayerGP']
goalieStats['RankAvgSavePctg']=round(goalieStats['AvgSavePctg'].rank(pct=True)*100,2)

goalieStats['LastFiveFlag'] = np.where(goalieStats['TeamGameNumber'] >= goalieStats['TeamGP']-5, 1, 0)

goalieStats['LastFiveAvgShotsAgainst']=goalieStats.groupby(['playerId','LastFiveFlag']).shotsAgainst.transform(np.sum)/5
goalieStats['LastFiveAvgShotsAgainst']=np.where(goalieStats['LastFiveFlag'] == 1, goalieStats['LastFiveAvgShotsAgainst'], 0)
goalieStats['LastFiveAvgShotsAgainst']=goalieStats.groupby('playerId').LastFiveAvgShotsAgainst.transform(np.max)

summaryGoalieStats=goalieStats[['Team','PlayerGP','firstName','lastName','RankAvgShotsAgainst','RankAvgGoalsAgainst','RankAvgSavePctg']].drop_duplicates()

summaryGoalieStats['GPRank']=summaryGoalieStats.groupby(['Team'])['PlayerGP'].rank(ascending=False).astype(int)
summaryGoalieStats=summaryGoalieStats[['Team','GPRank','firstName','lastName','RankAvgShotsAgainst','RankAvgGoalsAgainst','RankAvgSavePctg']].drop_duplicates()

summaryGoalieStats=summaryGoalieStats.rename(columns={"firstName": "GoalieFirstName",'lastName':'GoalieLastName','Team':'GoalieteamAbbrev'})
summaryGoalieStats.head()

,GoalieteamAbbrev,GPRank,GoalieFirstName,GoalieLastName,RankAvgShotsAgainst,RankAvgGoalsAgainst,RankAvgSavePctg
0,CHI,1,Spencer,Knight,98.49,40.19,85.72
1,FLA,1,Sergei,Bobrovsky,26.00,52.10,35.31
2,PIT,3,Arturs,Silovs,42.06,78.38,10.86
3,NYR,1,Igor,Shesterkin,62.59,25.50,70.30
4,COL,1,Scott,Wedgewood,32.12,5.98,79.56

In [15]:
full=todaysSkaters.merge(summaryGoalieStats
                         [summaryGoalieStats['GPRank']==1]
                         , left_on='Opponent', right_on='GoalieteamAbbrev', how='left'
                         ).drop(columns=['GoalieteamAbbrev','GPRank'])
full['lastfivemargin']=full['LastFiveAvgShots']-full['NoOutliersAvgSOG']

full['locationmargin']=full['avgshotshomevaway']-full['NoOutliersAvgSOG']
full['heatermargin']=full['LastFiveAvgShots']-full['LastTenAvgShots']
full['fixedmargin']=full['lastfivemargin']-full['heatermargin']
full['goalieweight']=2*((full['RankAvgShotsAgainst']-50)/100)
full['combinedmargin']=full['locationmargin']+full['fixedmargin']+full['goalieweight']

full['A_Standardized'] = (full['combinedmargin'] - full['combinedmargin'].mean()) / (full['combinedmargin'].std())

full['overrated'] = np.where(full['A_Standardized']<0,full['NoOutliersAvgSOG']-abs(full['A_Standardized']),
abs(full['A_Standardized'])-full['NoOutliersAvgSOG'])

full=full[abs(full['overrated'])>0.79]

full['aboveexpected']=full['overrated']/full['NoOutliersAvgSOG']

full=full[['lastName','firstName','Team', 'NoOutliersAvgSOG','combinedmargin'
,'A_Standardized','overrated','aboveexpected','fixedmargin','goalieweight',
'Avgtoi','position', 'HomeFlag','Opponent','heatermargin',  'LastFiveAvgShots', 'LastTenAvgShots',
'lastfivemargin','avgshotshomevaway','locationmargin','RankAvgShotsAgainst'
]].drop_duplicates().rename(columns={"NoOutliersAvgSOG": "ExpectedSOG",
        "avgshotshomevaway": "avgshotbyLoc"}).round(2)


todaysdate=str(pd.Timestamp.now().date())
full.to_excel(todaysdate+'skaterstats.xlsx', index=False, engine='xlsxwriter')

In [16]:
#full.insert(loc=1, column='new_col', value=[str('test') for i in range(0,len(full))])
print(len(full))
full.sort_values(by=['aboveexpected','overrated']
    #by=['ExpectedSOG']
                        , ascending=False #True #False #or True for players trending down
                       ).reset_index(drop=True).head(25)

212

,lastName,firstName,Team,ExpectedSOG,combinedmargin,A_Standardized,overrated,aboveexpected,fixedmargin,goalieweight,Avgtoi,position,HomeFlag,Opponent,heatermargin,LastFiveAvgShots,LastTenAvgShots,lastfivemargin,avgshotbyLoc,locationmargin,RankAvgShotsAgainst
0,Bratt,Jesper,NJD,2.18,-0.66,-0.02,2.16,0.99,-0.28,-0.84,18.70,L,0,UTA,0.3,2.2,1.9,0.02,2.65,0.47,7.85
1,Toews,Devon,COL,2.05,-0.65,-0.01,2.03,0.99,-0.45,0.34,22.39,D,1,WPG,0.0,1.6,1.6,-0.45,1.50,-0.55,67.24
2,Duchene,Matt,DAL,1.50,-0.66,-0.02,1.48,0.99,-1.50,0.59,15.50,C,0,ANA,0.0,0.0,0.0,-1.50,1.75,0.25,79.70
3,Horvat,Bo,NYI,3.71,-0.71,-0.06,3.65,0.98,-0.31,0.25,20.99,C,1,VAN,1.2,4.6,3.4,0.89,3.07,-0.64,62.59
4,Trouba,Jacob,ANA,2.06,-0.67,-0.03,2.02,0.98,-0.56,0.41,22.65,D,1,DAL,-0.5,1.0,1.5,-1.06,1.53,-0.53,70.35
5,Morrissey,Josh,WPG,1.76,-0.67,-0.03,1.73,0.98,0.04,-0.36,24.34,D,0,COL,-0.4,1.4,1.8,-0.36,1.41,-0.35,32.12
6,Mintyukov,Pavel,ANA,1.33,-0.66,-0.02,1.31,0.98,-0.73,0.41,16.67,D,1,DAL,-0.2,0.4,0.6,-0.93,1.00,-0.33,70.35
7,Hischier,Nico,NJD,2.27,-0.71,-0.06,2.21,0.97,0.23,-0.84,20.87,C,0,UTA,-0.1,2.4,2.5,0.13,2.18,-0.09,7.85
8,Hronek,Filip,VAN,1.61,-0.68,-0.04,1.57,0.97,-0.71,0.47,24.26,D,0,NYI,0.1,1.0,0.9,-0.61,1.17,-0.44,73.49
9,Gudas,Radko,ANA,1.47,-0.71,-0.06,1.41,0.96,-1.47,0.41,16.99,D,1,DAL,0.0,0.0,0.0,-1.47,1.82,0.35,70.35
10,Connor,Kyle,WPG,3.61,-0.85,-0.18,3.43,0.95,0.29,-0.36,20.74,L,0,COL,-0.3,3.6,3.9,-0.01,2.82,-0.79,32.12
11,Pelech,Adam,NYI,1.65,-0.73,-0.08,1.57,0.95,-0.45,0.25,20.42,D,1,VAN,0.6,1.8,1.2,0.15,1.12,-0.53,62.59
12,Svechnikov,Andrei,CAR,2.76,-0.82,-0.15,2.61,0.94,-0.26,-0.48,16.81,R,0,FLA,-0.1,2.4,2.5,-0.36,2.69,-0.07,26.00
13,Walker,Sean,CAR,2.35,-0.80,-0.13,2.21,0.94,0.15,-0.48,22.93,D,0,FLA,0.3,2.8,2.5,0.45,1.88,-0.47,26.00
14,Rodrigues,Evan,FLA,1.94,-0.81,-0.14,1.80,0.93,0.26,-0.91,16.57,C,1,CAR,0.2,2.4,2.2,0.46,1.79,-0.15,4.56
15,Jones,Seth,FLA,1.76,-0.78,-0.12,1.64,0.93,-0.16,-0.91,23.69,D,1,CAR,0.2,1.8,1.6,0.04,2.05,0.29,4.56
16,Meier,Timo,NJD,2.75,-0.91,-0.23,2.52,0.92,-0.75,-0.84,18.76,R,0,UTA,-0.4,1.6,2.0,-1.15,3.43,0.68,7.85
17,Cooley,Logan,UTA,2.21,-0.85,-0.18,2.03,0.92,-1.41,0.10,18.07,C,1,NJD,-0.8,0.0,0.8,-2.21,2.67,0.46,54.88
18,Mercer,Dawson,NJD,2.08,-0.82,-0.16,1.92,0.92,-0.08,-0.84,18.96,C,0,UTA,0.4,2.4,2.0,0.32,2.18,0.10,7.85
19,Martinook,Jordan,CAR,1.65,-0.78,-0.13,1.52,0.92,0.15,-0.48,14.64,L,0,FLA,0.4,2.2,1.8,0.55,1.19,-0.46,26.00
20,Bennett,Sam,FLA,2.00,-0.85,-0.18,1.82,0.91,0.20,-0.91,17.04,C,1,CAR,0.8,3.0,2.2,1.00,1.86,-0.14,4.56
21,Pulock,Ryan,NYI,1.53,-0.80,-0.14,1.39,0.91,-0.53,0.25,20.98,D,1,VAN,-0.2,0.8,1.0,-0.73,1.00,-0.53,62.59
22,Hughes,Quinn,VAN,2.65,-0.94,-0.25,2.40,0.90,-1.05,0.47,27.62,D,0,NYI,-1.4,0.2,1.6,-2.45,2.29,-0.36,73.49
23,Samoskevich,Mackie,FLA,2.35,-0.90,-0.22,2.12,0.90,0.35,-0.91,14.75,R,1,CAR,-0.3,2.4,2.7,0.05,2.00,-0.35,4.56
24,Pettersson,Elias,VAN,1.84,-0.85,-0.18,1.66,0.90,-1.04,0.47,20.52,C,0,NYI,-0.6,0.2,0.8,-1.64,1.56,-0.28,73.49

In [17]:
# pip install xlsxwriter

In [18]:
# margin=full
# margin['lastfivemargin']=margin['LastFiveAvgShots']-margin['ExpectedSOG']


# margin=margin[['teamAbbrev', 'HomeFlag', 'firstName', 'lastName', 'ExpectedSOG','AvgShotsSznByLoc',
#        'LastFiveAvgShots', 'LastTenAvgShots', 'Opponent', 'RankAvgShotsAgainst',
#         'GoalieLastName',	'avgshotsvsOppAtLoc',	'AvgShotsAgainstThisOpp',
#         'SeasonAvgSOG', 'playerId', 
#        'RankAvgGoalsAgainst', 'RankAvgSavePctg', 'lastfivemargin']]

# margin.sort_values(by=['lastfivemargin']
#                         , ascending=False #or True for players trending down
#                         #, ascending=True
#                        ).reset_index(drop=True).head(25)

In [19]:
# margin['locationmargin']=margin['AvgShotsSznByLoc']-margin['ExpectedSOG']

# margin.sort_values(by=['locationmargin']
#                         , ascending=False #or True for players trending down
#                         #, ascending=True
#                        ).reset_index(drop=True).head(25)

In [20]:
# margin['combinedmargin']=margin['lastfivemargin']+margin['locationmargin']

# margin[['firstName',	'lastName','teamAbbrev',	'HomeFlag','combinedmargin',
# 		'ExpectedSOG','LastFiveAvgShots',	'AvgShotsSznByLoc'	,
#         	'LastTenAvgShots',	'Opponent',	'RankAvgShotsAgainst',	'GoalieLastName',
#             			'SeasonAvgSOG']].sort_values(by=['combinedmargin']
#                         , ascending=False #or True for players trending down
#                         #, ascending=True
#                        ).reset_index(drop=True).head(25)

In [21]:
# link = BaseURL + '/v1/partner-game/US/now'
# f = requests.get(link)
# f.json()['games'][0]['homeTeam']
# # df=pd.DataFrame(f.json()['games'][0])
# # df